major cleanup and rewrite of parts to fix my prior bad coding

diff --git a/pgsql-backup b/pgsql-backup
--- a/pgsql-backup
+++ b/pgsql-backup
@@ -3,13 +3,6 @@
 # Original script:	MySQL Backup Script
 #			VER. 2.5 - http://sourceforge.net/projects/automysqlbackup/
 #			Copyright (c) 2002-2003 wipe_out@lycos.co.uk
-# -----------
-# CHANGELOG
-# -----------
-# 090106 - Hacked by PHS to do PostgreSQL Databases instead of MySQL
-# 090819 - Minor fixes, added configuration option for CONNECT_DB
-# 090914 - Removed use of $PATH in favour of using explicitly set path variables within options.conf
-# 091210 - Added support for using a password for the database user. See the DB_PASS config option
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -30,26 +23,77 @@
 VER=0.9.7
 
 # Path to options file
-OPTIONS_FILE='/etc/pgsql-backup/options.conf'
-
-#=====================================================================
-#=====================================================================
-#=====================================================================
-#
-# YOU SHOULD NOT NEED TO MODIFY ANYTHING BELOW HERE!!
-#
-#=====================================================================
-#=====================================================================
-#=====================================================================
-#
-# Make sure our config file exists
-if [ -e "$OPTIONS_FILE" ] ; then
-	source $OPTIONS_FILE
+if [ -f '~/.pgsql-backup.conf' ] ; then
+	rc_fname='~/.pgsql-backup.conf'
+elif [ -f '/etc/pgsql-backup.conf' ] ; then
+	rc_fname='/etc/pgsql-backup.conf'
+elif [ -f '/etc/pgsql-backup/options.conf' ] ; then
+	rc_fname='/etc/pgsql-backup/options.conf'
 else
-	echo "Failed to find the options file: $OPTIONS_FILE"
+	echo 'Configuration file not found!'
 	exit 1
 fi
-#
+
+# Load the configuration file
+if [ -r "$rc_fname" ] ; then
+	source $rc_fname
+else
+	echo "Unable to read configuration file: $rc_fname"
+	exit 1
+fi
+
+# IO redirection for logging.
+touch $log_stdout
+exec 6>&1           # Link file descriptor #6 with stdout.
+exec > $log_stdout     # stdout replaced with file $log_stdout.
+touch $log_stderr
+exec 7>&2           # Link file descriptor #7 with stderr.
+exec 2> $log_stderr     # stderr replaced with file $log_stderr.
+
+echo "Using configuration file '$rc_fname'"
+
+# Validate the configuration
+[[ -z "$MAILADDR" ]]	&& MAILADDR='root@localhost'
+[[ -z "$DBHOST" ]]		&& DBHOST='localhost'
+[[ -z "$DBNAMES" ]]		&& DBNAMES='all'
+[[ -z "$MAILCONTENT" ]]	&& MAILCONTENT='stdout'
+[[ -z "$MAXATTSIZE" ]]	&& MAXATTSIZE='4096'
+
+# Make sure our binaries are good
+PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+[[ -z "$PG_DUMP" ]]	&& PG_DUMP=$(which pg_dump)
+[[ -z "$PSQL" ]]	&& PSQL=$(which psql)
+[[ -z "$RM" ]]		&& RM=$(which rm)
+[[ -z "$MKDIR" ]]	&& MKDIR=$(which mkdir)
+[[ -z "$DATE" ]]	&& DATE=$(which date)
+[[ -z "$LN" ]]		&& LN=$(which ln)
+[[ -z "$SED" ]]		&& SED=$(which sed)
+[[ -z "$DU" ]]		&& DU=$(which du)
+[[ -z "$GREP" ]]	&& GREP=$(which grep)
+[[ -z "$CAT" ]]		&& CAT=$(which cat)
+[[ -z "$MAILX" ]]	&& MAILX=$(which mailx)
+[[ -z "$GZIP" ]]	&& GZIP=$(which gzip)
+[[ -z "$BZIP2" ]]	&& BZIP2=$(which bzip2)
+MISSING_BIN=''
+[[ -x "$PG_DUMP" ]]	|| MISSING_BIN="$MISSING_BIN pgdump not found: $PG_DUMP\n"
+[[ -x "$PSQL" ]]	|| MISSING_BIN="$MISSING_BIN psql not found: $PSQL\n"
+[[ -x "$RM" ]]		|| MISSING_BIN="$MISSING_BIN rm not found: $RM\n"
+[[ -x "$MKDIR" ]]	|| MISSING_BIN="$MISSING_BIN mkdir not found: $MKDIR\n"
+[[ -x "$DATE" ]]	|| MISSING_BIN="$MISSING_BIN date not found: $DATE\n"
+[[ -x "$LN" ]]		|| MISSING_BIN="$MISSING_BIN ln not found: $LN\n"
+[[ -x "$SED" ]]		|| MISSING_BIN="$MISSING_BIN sed not found: $SED\n"
+[[ -x "$DU" ]]		|| MISSING_BIN="$MISSING_BIN du not found: $DU\n"
+[[ -x "$GREP" ]]	|| MISSING_BIN="$MISSING_BIN grep not found: $GREP\n"
+[[ -x "$CAT" ]]		|| MISSING_BIN="$MISSING_BIN cat not found: $CAT\n"
+[[ -x "$MAILX" ]]	|| MISSING_BIN="$MISSING_BIN mail not found: $MAILX\n"
+[[ ! -x "$GZIP" -a "$COMP" = 'gzip' ]]		&& MISSING_BIN="$MISSING_BIN gzip not found: $GZIP\n"
+[[ ! -x "$BZIP2" -a "$COMP" = 'bzip2' ]]	&& MISSING_BIN="$MISSING_BIN bzip2 not found: $BZIP2\n"
+if [ -n "$MISSING_BIN" ] ; then
+	echo "Some required programs were not found. Please check $rc_fname to ensure correct paths are set."
+	echo "The missing files are:"
+	echo -e $MISSING_BIN
+fi
+
 # Make all config from options.conf READ-ONLY
 declare -r USERNAME
 declare -r DBHOST
@@ -76,72 +120,25 @@ declare -r GREP
 declare -r CAT
 declare -r MAILX
 
-# Make sure our binaries are good
-MISSING_BIN=''
-[ -x "$PG_DUMP" ]	|| MISSING_BIN="$MISSING_BIN pgdump not found: $PG_DUMP\n"
-[ -x "$PSQL" ]		|| MISSING_BIN="$MISSING_BIN psql not found: $PSQL\n"
-[ -x "$RM" ]		|| MISSING_BIN="$MISSING_BIN rm not found: $RM\n"
-[ -x "$MKDIR" ]		|| MISSING_BIN="$MISSING_BIN mkdir not found: $MKDIR\n"
-[ -x "$DATE" ]		|| MISSING_BIN="$MISSING_BIN date not found: $DATE\n"
-[ -x "$LN" ]		|| MISSING_BIN="$MISSING_BIN ln not found: $LN\n"
-[ -x "$SED" ]		|| MISSING_BIN="$MISSING_BIN sed not found: $SED\n"
-[ -x "$DU" ]		|| MISSING_BIN="$MISSING_BIN du not found: $DU\n"
-[ -x "$GREP" ]		|| MISSING_BIN="$MISSING_BIN grep not found: $GREP\n"
-[ -x "$CAT" ]		|| MISSING_BIN="$MISSING_BIN cat not found: $CAT\n"
-[ -x "$MAILX" ]		|| MISSING_BIN="$MISSING_BIN mail not found: $MAILX\n"
-[ ! -x "$GZIP" -a "$COMP" = 'gzip' ]	&& MISSING_BIN="$MISSING_BIN gzip not found: $GZIP\n"
-[ ! -x "$BZIP2" -a "$COMP" = 'bzip2' ]	&& MISSING_BIN="$MISSING_BIN bzip2 not found: $BZIP2\n"
-if [ -n "$MISSING_BIN" ] ; then
-	echo "Some required programs were not found. Please check $OPTIONS_FILE to ensure correct paths are set."
-	echo "The missing files are:"
-	echo -e $MISSING_BIN
-fi
-
-#PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/postgres/bin 
-FULLDATE=`$DATE +%Y-%m-%d_%Hh%Mm`			# Datestamp e.g 2002-09-21
+FULLDATE=`$DATE +%Y-%m-%d_%Hh%Mm`	# Datestamp e.g 2002-09-21
 DOW=`$DATE +%A`						# Day of the week e.g. Monday
 DNOW=`$DATE +%u`					# Day number of the week 1 to 7 where 1 represents Monday
 DOM=`$DATE +%d`						# Date of the Month e.g. 27
 M=`$DATE +%B`						# Month e.g January
 W=`$DATE +%V`						# Week Number e.g 37
-LOGFILE=$BACKUPDIR/$DBHOST-`$DATE +%N`.log		# Logfile Name
-LOGERR=$BACKUPDIR/ERRORS_$DBHOST-`$DATE +%N`.log	# Logfile Name
+log_stdout=$BACKUPDIR/$DBHOST-`$DATE +%N`.log		# Logfile Name
+log_stderr=$BACKUPDIR/ERRORS_$DBHOST-`$DATE +%N`.log	# Logfile Name
 BACKUPFILES=""
 OPT="--blobs --format=${DUMPFORMAT}"			# OPT string for use with pg_dump
 
 # Create required directories
-if [ ! -e "$BACKUPDIR" ] ; then		# Check Backup Directory exists.
-	$MKDIR -p "$BACKUPDIR"
-fi
-
-if [ ! -e "$BACKUPDIR/daily" ] ; then	# Check Daily Directory exists.
-	$MKDIR -p "$BACKUPDIR/daily"
-fi
-
-if [ ! -e "$BACKUPDIR/weekly" ]	; then	# Check Weekly Directory exists.
-	$MKDIR -p "$BACKUPDIR/weekly"
-fi
-
-if [ ! -e "$BACKUPDIR/monthly" ] ; then	# Check Monthly Directory exists.
-	$MKDIR -p "$BACKUPDIR/monthly"
-fi
-
+[[ ! -e "$BACKUPDIR/daily" ]]	&& $MKDIR -p "$BACKUPDIR/daily"
+[[ ! -e "$BACKUPDIR/weekly" ]]	&& $MKDIR -p "$BACKUPDIR/weekly"
+[[ ! -e "$BACKUPDIR/monthly" ]]	&& $MKDIR -p "$BACKUPDIR/monthly"
 if [ "$LATEST" = "yes" ] ; then
-if [ ! -e "$BACKUPDIR/latest" ]	; then # Check Latest Directory exists.
-		$MKDIR -p "$BACKUPDIR/latest"
-	fi
-	eval $RM -f "$BACKUPDIR/latest/*"
+	[[ ! -e "$BACKUPDIR/latest" ]] && $MKDIR -p "$BACKUPDIR/latest"
+	$RM -f $BACKUPDIR/latest/*
 fi
-
-# IO redirection for logging.
-touch $LOGFILE
-exec 6>&1           # Link file descriptor #6 with stdout.
-                    # Saves stdout.
-exec > $LOGFILE     # stdout replaced with file $LOGFILE.
-touch $LOGERR
-exec 7>&2           # Link file descriptor #7 with stderr.
-                    # Saves stderr.
-exec 2> $LOGERR     # stderr replaced with file $LOGERR.
 
 # Output Extension (depends on the output format)
 if [ "$DUMPFORMAT" = 'tar' ] ; then
@@ -160,30 +157,32 @@ OPT="$OPT --format=${DUMPFORMAT}"
 
 # Database dump function
 dbdump () {
+	local _args="$1"
+	local _output_fname="$2"
 	export PGPASSWORD="$DB_PASS"
-	$PG_DUMP --username=$USERNAME --host=$DBHOST $OPT $1 > $2
+	$PG_DUMP --username=$USERNAME --host=$DBHOST $OPT $_args > $_output_fname
 	return $?
 }
 
 # Compression function plus latest copy
 SUFFIX=""
 compression () {
+	local _fname="$1"
+
 	if [ "$COMP" = "gzip" ]; then
-		$GZIP -f "$1"
-		echo
-		echo Backup Information for "$1"
-		$GZIP -l "$1.gz"
+		echo Backup Information for "$_fname"
+		$GZIP -f "$_fname"
+		$GZIP -l "$_fname.gz"
 		SUFFIX=".gz"
 	elif [ "$COMP" = "bzip2" ]; then
-		echo Compression information for "$1.bz2"
-		$BZIP2 -f -v $1 2>&1
+		echo Compression information for "$_fname.bz2"
+		$BZIP2 -f -v $_fname 2>&1
 		SUFFIX=".bz2"
 	else
 		echo "No compression option set, check advanced settings"
 	fi
 	if [ "$LATEST" = "yes" ]; then
-		#cp $1$SUFFIX "$BACKUPDIR/latest/"
-		$LN $1$SUFFIX "$BACKUPDIR/latest/"
+		$LN -f ${_fname}${SUFFIX} "$BACKUPDIR/latest/"
 	fi	
 	return 0
 }
@@ -201,7 +200,6 @@ if [ "$PREBACKUP" ]
 	echo ======================================================================
 	echo
 fi
-
 
 if [ "$SEPDIR" = "yes" ]; then # Check if CREATE DATABSE should be included in Dump
 	if [ "$CREATE_DATABASE" = "no" ]; then
@@ -231,91 +229,83 @@ if [ "$DBNAMES" = "all" ]; then
 		DBNAMES=`echo $DBNAMES | $SED "s/\b$exclude\b//g"`
 	done
 
-        MDBNAMES=$DBNAMES
+	MDBNAMES=$DBNAMES
 fi
 
-echo ======================================================================
-echo AutoPostgreSQLBackup VER $VER
-echo   Based on: http://sourceforge.net/projects/automysqlbackup/
-echo 
-echo Backup of PostgreSQL Database Server - $HOST
-echo ======================================================================
+$CAT <<EOT
+======================================================================
+pgsql-backup VER $VER
+   Based on AutoMySQLBackup
+   http://sourceforge.net/projects/automysqlbackup/
+======================================================================
+Backup of PostgreSQL Database Server - $HOST
+Started $($DATE)
+======================================================================
+EOT
 
-echo Backup Start Time `$DATE`
-echo ======================================================================
-# Monthly Full Backup of all Databases
+# Monthly Full Backup of all Databases on the 1st of the month
 if [ $DOM = "01" ]; then
 	for MDB in $MDBNAMES ; do
-		# Prepare $DB for using
-	        MDB="`echo $MDB | $SED 's/%/ /g'`"
+		MDB="`echo $MDB | $SED 's/%/ /g'`"
 
-		if [ ! -e "$BACKUPDIR/monthly/$MDB" ] ; then		# Check Monthly DB Directory exists.
-			$MKDIR -p "$BACKUPDIR/monthly/$MDB"
-		fi
 		echo Monthly Backup of $MDB...
+
+		[[ ! -e "$BACKUPDIR/monthly/$MDB" ]] && $MKDIR -p "$BACKUPDIR/monthly/$MDB"
 		dbdump "${MDB}" "${BACKUPDIR}/monthly/${MDB}/${MDB}_${FULLDATE}.${M}.${MDB}.${OUTEXT}"
 		compression "${BACKUPDIR}/monthly/${MDB}/${MDB}_${FULLDATE}.${M}.${MDB}.${OUTEXT}"
 		BACKUPFILES="${BACKUPFILES} ${BACKUPDIR}/monthly/${MDB}/${MDB}_${FULLDATE}.${M}.${MDB}.${OUTEXT}${SUFFIX}"
-		echo ----------------------------------------------------------------------
+		echo '----------------------------------------------------------------------'
 	done
 fi
 
 for DB in $DBNAMES ; do
-	# Prepare $DB for using
 	DB="`echo $DB | $SED 's/%/ /g'`"
 	
 	# Create Seperate directory for each DB
-	if [ ! -e "$BACKUPDIR/daily/$DB" ] ; then		# Check Daily DB Directory exists.
-		$MKDIR -p "$BACKUPDIR/daily/$DB"
-	fi
+	[[ ! -e "$BACKUPDIR/daily/$DB" ]]	&& $MKDIR -p "$BACKUPDIR/daily/$DB"
+	[[ ! -e "$BACKUPDIR/weekly/$DB" ]]	&& $MKDIR -p "$BACKUPDIR/weekly/$DB"
 	
-	if [ ! -e "$BACKUPDIR/weekly/$DB" ] ; then		# Check Weekly DB Directory exists.
-		$MKDIR -p "$BACKUPDIR/weekly/$DB"
-	fi
-	
-	# Weekly Backup
-	if [ $DNOW = $DOWEEKLY ]; then
-		echo Weekly Backup of Database \( $DB \)
-		echo Rotating 5 weeks Backups...
-			if [ "$W" -le 05 ];then
+	if [ $DNOW = $DOWEEKLY ] ; then
+		# Weekly Backup
+		echo "Weekly Backup of Database '$DB'"
+		echo "Rotating 5 weeks Backups..."
+			if [ "$W" -le 05 ] ; then
 				REMW=`expr 48 + $W`
 			elif [ "$W" -lt 15 ];then
 				REMW=0`expr $W - 5`
 			else
 				REMW=`expr $W - 5`
 			fi
-		eval $RM -f "$BACKUPDIR/weekly/$DB/${DB}_week.$REMW.*" 
+		$RM -f $BACKUPDIR/weekly/$DB/${DB}_week.$REMW.*
 		echo
 		dbdump "$DB" "$BACKUPDIR/weekly/$DB/${DB}_week.$W.$FULLDATE.${OUTEXT}"
 		compression "$BACKUPDIR/weekly/$DB/${DB}_week.$W.$FULLDATE.${OUTEXT}"
 		BACKUPFILES="$BACKUPFILES $BACKUPDIR/weekly/$DB/${DB}_week.$W.$FULLDATE.${OUTEXT}$SUFFIX"
-		echo ----------------------------------------------------------------------
-	
-	# Daily Backup
+		echo '----------------------------------------------------------------------'
 	else
-		echo Daily Backup of Database \( $DB \)
-		echo Rotating last weeks Backup...
-		eval $RM -f "$BACKUPDIR/daily/$DB/*.$DOW.*" 
+		# Daily Backup
+		echo "Daily Backup of Database '$DB'"
+		echo "Rotating last weeks Backup..."
+		$RM -f $BACKUPDIR/daily/$DB/*.$DOW.*
 		echo
 		dbdump "$DB" "$BACKUPDIR/daily/$DB/${DB}_$FULLDATE.$DOW.${OUTEXT}"
 		compression "$BACKUPDIR/daily/$DB/${DB}_$FULLDATE.$DOW.${OUTEXT}"
 		BACKUPFILES="$BACKUPFILES $BACKUPDIR/daily/$DB/${DB}_$FULLDATE.$DOW.${OUTEXT}$SUFFIX"
-		echo ----------------------------------------------------------------------
+		echo '----------------------------------------------------------------------'
 	fi
 done
 
-echo Backup End `$DATE`
-echo ======================================================================
-
-echo Total disk space used for backup storage..
-echo Size - Location
-echo `$DU -hs "$BACKUPDIR"`
-echo
-echo ======================================================================
+$CAT <<EOT
+Backup End `$DATE`
+======================================================================
+Total disk space used for backup storage..
+Size - Location
+$($DU -hs "$BACKUPDIR")
+======================================================================
+EOT
 
 # Run command when we're done
-if [ "$POSTBACKUP" ]
-	then
+if [ "$POSTBACKUP" ] ; then
 	echo ======================================================================
 	echo "Postbackup command output."
 	echo
@@ -328,48 +318,60 @@ fi
 exec 1>&6 6>&-      # Restore stdout and close file descriptor #6.
 exec 1>&7 7>&-      # Restore stdout and close file descriptor #7.
 
-if [ "$MAILCONTENT" = "files" ] ; then
-	if [ -s "$LOGERR" ] ; then
+case "$MAILCONTENT" in
+'files')
+	if [ -s "$log_stderr" ] ; then
 		# Include error log if is larger than zero.
-		BACKUPFILES="$BACKUPFILES $LOGERR"
+		BACKUPFILES="$BACKUPFILES $log_stderr"
 		ERRORNOTE="WARNING: Error Reported - "
 	fi
 	# Get backup size
-	ATTSIZE=`$DU -c $BACKUPFILES | $GREP "[[:digit:][:space:]]total$" | $SED s/\s*total//`
+	ATTSIZE=$($DU -c $BACKUPFILES | $GREP "[[:digit:][:space:]]total$" | $SED s/\s*total//)
 	if [ $MAXATTSIZE -lt $ATTSIZE ] ; then
-		$CAT "$LOGFILE" | $MAILX -s "WARNING! - PostgreSQL Backup exceeds set maximum attachment size on $HOST - $FULLDATE" $MAILADDR
+		$CAT "$log_stdout" | $MAILX -s "WARNING! - PostgreSQL Backup exceeds set maximum attachment size on $HOST - $FULLDATE" $MAILADDR
 	fi
-elif [ "$MAILCONTENT" = "log" ] ; then
-	$CAT "$LOGFILE" | $MAILX -s "PostgreSQL Backup Log for $HOST - $FULLDATE" $MAILADDR
-	if [ -s "$LOGERR" ] ; then
-		$CAT "$LOGERR" | $MAILX -s "ERRORS REPORTED: PostgreSQL Backup error Log for $HOST - $FULLDATE" $MAILADDR
-	fi	
-elif [ "$MAILCONTENT" = "quiet" ] ; then
-	if [ -s "$LOGERR" ] ; then
-		$CAT "$LOGERR" | $MAILX -s "ERRORS REPORTED: PostgreSQL Backup error Log for $HOST - $FULLDATE" $MAILADDR
-		$CAT "$LOGFILE" | $MAILX -s "PostgreSQL Backup Log for $HOST - $FULLDATE" $MAILADDR
+;;
+'log')
+	$CAT "$log_stdout" | $MAILX -s "PostgreSQL Backup Log for $HOST - $FULLDATE" $MAILADDR
+	if [ -s "$log_stderr" ] ; then
+		$CAT "$log_stderr" | $MAILX -s "ERRORS REPORTED: PostgreSQL Backup error Log for $HOST - $FULLDATE" $MAILADDR
 	fi
-else
-	if [ -s "$LOGERR" ] ; then
-		$CAT "$LOGFILE"
-		echo
-		echo "!!!!!! WARNING !!!!!!"
-		echo "Errors reported during AutoPostgreSQLBackup execution.. Backup failed"
-		echo "Error log below.."
-		$CAT "$LOGERR"
+;;
+'quiet')
+	if [ -s "$log_stderr" ] ; then
+		$MAILX -s "ERRORS REPORTED: PostgreSQL Backup error Log for $HOST - $FULLDATE" $MAILADDR <<EOT
+=============================================
+!!!!!! WARNING !!!!!!
+Errors reported during AutoPostgreSQLBackup execution... BACKUP FAILED.
+$($CAT $log_stderr)
+=============================================
+Full Log Below
+=============================================
+$($CAT $log_stdout)
+=============================================
+EOT
+	fi
+;;
+*)
+	if [ -s "$log_stderr" ] ; then
+		$CAT <<EOT
+=============================================
+!!!!!! WARNING !!!!!!
+Errors reported during AutoPostgreSQLBackup execution... BACKUP FAILED.
+$($CAT $log_stderr)
+=============================================
+Full Log Below
+=============================================
+$($CAT $log_stdout)
+=============================================
 	else
-		$CAT "$LOGFILE"
-	fi	
-fi
-
-if [ -s "$LOGERR" ] ; then
-	STATUS=1
-else
-	STATUS=0
-fi
+		$CAT "$log_stdout"
+	fi
+;;
+esac
 
 # Clean up Logfile
-eval $RM -f "$LOGFILE"
-eval $RM -f "$LOGERR"
+eval $RM -f "$log_stdout"
+eval $RM -f "$log_stderr"
 
-exit $STATUS
+exit [[ -s "$log_stderr" ]]
